version: '3.9'

services:
  backend:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  frontend:
    build: frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend
